const state={events:[],year:2026,category:"all",selected:null,markers:[]};
const categoryClass=c=>c.includes("war")||c.includes("political-conflict")||c.includes("political-violence")?"war":c.includes("pandemic")?"pandemic":c.includes("famine")?"famine":c.includes("natural-disaster")||c.includes("earthquake")||c.includes("tsunami")||c.includes("cyclone")?"natural":c.includes("genocide")?"genocide":"other";
const categoryLabel=c=>({war:"Krieg",pandemic:"Pandemie",famine:"Hungersnot",natural:"Naturkatastrophe",genocide:"Völkermord",other:"Sonstige"})[c]||c;
const formatDeaths=e=>{const n=e.deaths;return n.min===n.max?Intl.NumberFormat("de-DE").format(n.min):Intl.NumberFormat("de-DE").format(n.min)+"–"+Intl.NumberFormat("de-DE").format(n.max)};
function syncYear(value){state.year=Number(value);document.querySelector("#yearValue").textContent=state.year;document.querySelector("#year").value=state.year;document.querySelector("#year2").value=state.year;renderMarkers()}
function renderMetrics(){document.querySelector("#eventCount").textContent=state.events.filter(matches).length;const total=state.events.filter(matches).reduce((s,e)=>s+(e.deaths.max||0),0);document.querySelector("#deathMax").textContent=Intl.NumberFormat("de-DE",{notation:"compact",maximumFractionDigits:1}).format(total)}
function matches(e){const inTime=Number(e.start)<=state.year&&Number(e.end)>=state.year;const inCat=state.category==="all"||e.category.includes(state.category)||categoryClass(e.category)===state.category;return inTime&&inCat}
function renderMarkers(){state.markers.forEach(m=>m.remove());state.markers=[];state.events.filter(matches).forEach(e=>{const cls=categoryClass(e.category);const icon=L.divIcon({className:"",html:'<div class="marker marker-'+cls+'"></div>',iconSize:[15,15],iconAnchor:[7,7]});const m=L.marker([e.lat,e.lng],{icon}).addTo(map);m.bindPopup("<b>"+e.name+"</b><br>"+e.start+(e.end!==e.start?"–"+e.end:"")+"<br>"+formatDeaths(e)+" deaths");m.on("click",()=>selectEvent(e.id));state.markers.push(m)});renderMetrics()}
function selectEvent(id){const e=state.events.find(x=>x.id===id);if(!e)return;state.selected=e;document.querySelector("#details").innerHTML='<div class="section"><h2>// SELECTED EVENT</h2><div class="event-title">'+e.name+'</div><div class="event-meta">'+e.start+(e.end!==e.start?" — "+e.end:"")+" · "+e.region+'</div><div class="death">'+formatDeaths(e)+'<span style="font-size:10px;color:var(--muted)"> EST. DEATHS</span></div><div class="confidence">CONFIDENCE: '+e.confidence.toUpperCase()+'</div></div><div class="section"><h2>// DESCRIPTION</h2><div class="desc">'+e.description+'</div></div><div class="section"><h2>// ACTORS</h2><div class="desc">'+(e.actors.length?e.actors.map(x=>"• "+x).join("<br>"):"No actor attribution in this entry.")+'</div></div><div class="section"><h2>// RELIGIOUS FACTORS</h2><div class="metric"><span>RELEVANCE</span><b>'+e.religious_factors.relevance.toUpperCase()+'</b></div><div class="desc" style="margin-top:8px">'+e.religious_factors.summary+'</div></div><div class="section"><h2>// SOURCES</h2>'+e.sources.map(s=>'<a class="source" href="'+s.url+'" target="_blank" rel="noopener">'+s.title+'</a>').join("")+'</div>';map.flyTo([e.lat,e.lng],Math.max(map.getZoom(),4),{duration:.7})}
function renderChips(){document.querySelectorAll("[data-cat]").forEach(b=>b.classList.toggle("active",b.dataset.cat===state.category))}
async function init(){const r=await fetch("data/events.json");state.events=await r.json();window.map=L.map("map",{worldCopyJump:true,minZoom:2,maxZoom:18,tap:true}).setView([20,0],2);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);renderMarkers();setTimeout(()=>map.invalidateSize(),150);window.addEventListener("resize",()=>map.invalidateSize());window.addEventListener("orientationchange",()=>setTimeout(()=>map.invalidateSize(),250));document.querySelector("#year").addEventListener("input",e=>syncYear(e.target.value));document.querySelector("#year2").addEventListener("input",e=>syncYear(e.target.value));document.querySelectorAll("[data-cat]").forEach(b=>b.addEventListener("click",()=>{state.category=b.dataset.cat;renderChips();renderMarkers()}));document.querySelector("#reset").addEventListener("click",()=>{state.year=2026;state.category="all";document.querySelector("#yearValue").textContent=2026;document.querySelector("#year").value=2026;document.querySelector("#year2").value=2026;renderChips();renderMarkers();document.querySelector("#details").innerHTML='<div class="section"><h2>// SELECT AN EVENT</h2><div class="empty">Select a marker on the map to inspect the event, estimated deaths, actors, religious context and sources.</div></div>'});}
init().catch(e=>{document.querySelector("#details").innerHTML='<div class="empty">DATA ERROR: '+e.message+'</div>'});